### ISSUE TITLE
Android nabto library 64 bit support

### ISSUE THREAD

**Issue by ghost** [nabto/android-client-api#4]
Hello Nabto Team,
We are using your libraries in our Android Project. 
In Gradle.Build we have written as:
implementation 'com.nabto.android:nabto-api:1.4.0'

Now when we try to Analyze apk by Google Guidance we have found that libraries are 32-bit supported and Google ask for 64-bit library.
<img width="736" alt="analyze" src="https://user-images.githubusercontent.com/85494713/135222105-be7396c7-34e3-4957-9dcd-ac0e2e391400.png">

We followed this link by Google for 64-bit:
[https://developer.android.com/distribute/best-practices/develop/64-bit]

So we need a library which support 64-bit.
Kindly provide a implementation name of Nabto which we can write in our Project Gradle.Build file.

**Comment by nabto** [comment]
Hi there,

You are using quite an old Nabto library for Android, please upgrade to the latest (1.6.0), it has 64-bit support. 

Ulrik
