### ISSUE TITLE
I can't import Library

### ISSUE THREAD

**Issue by cgowthamanmca** [nabto/android-client-api#5]
![Screenshot from 2022-08-08 10-08-37](https://user-images.githubusercontent.com/34183706/183340364-3190b8a6-834c-4568-b64e-3863bec81081.png)
![Screenshot from 2022-08-08 10-08-41](https://user-images.githubusercontent.com/34183706/183340381-45533b4b-d026-4647-88d8-bf20cb054b07.png)

I am added library in gradle .but can't import it

**Comment by gammelby** [comment]
Hi there,

Can you please post the full output from gradle when you do a clean build?

Thanks!
